# Site settings
title: NGUYEN HA ANH
email: anhnguyenha06@gmail.com
url: "https://k632412820005-hash.github.io"
description: "Portfolio học phần Cơ sở dữ liệu - Nguyễn Hà Anh - Sinh viên Khoá 63 chuyên ngành Kế toán - Kiểm toán Trường Đại học Ngoại thương FTU Hà Nội"
skills: "TIN313 - FOREIGN TRADE UNIVERSITY"
meta_author: Nguyễn Hà Anh

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 8d6e63
  primary-rgb: "141,110,99"
  secondary: 4e342e
  secondary-dark: 3e2723

# Footer settings
footer:
  copyright: Ha Anh Nguyen
  location: Adress
  social: Around the Web
  credits: Course

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/tuanm.huu/
  - title: instagram
    url: https://www.instagram.com/kl.ngha/
  - title: github
    url: https://github.com/k632412820005-hash

# Postal address (add as many lines as necessary)
address:
  - line: Ha Noi, Viet Nam

# Credits content
credits: 'TIN313 - Mr. Tran Cong Minh'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
